### ISSUE TITLE
gameInProgress state not updating in GameBoard 

### ISSUE THREAD

**Issue by alexhoffman-dev** [TellemBigAlsentya/tic-tac-toe-react#1]
App.js has a gameBuild state that is passed down to GameBoard child and keeps track of the boardSize and gameInProgress. When GameBoard renders as a result of the players adding a boardSize via the PlayerInput component, the boardSize state is set and never changes. The gameInProgress state however does change via the gameOver function call in App.js. The issue I'm having then is that when the gameOver function is called when any of the win or draw conditions are met, the state is updated in App.js but not passed down to GameBoard via props dynamically. Since the gameInProgress boolean is integral to the apps business logic, it not re-rendering or being passed down as a 'false' once the game is 'over,' is a problem. Curious if you think this is an architectural shortcoming or I'm missing a core concept here?

**Comment by Luke9389** [comment]
The problem here is with this code (we discussed this yesterday, but I figure it's best to have it here on the issue as well). 

https://github.com/TellemBigAlsentya/tic-tac-toe-react/blob/5455b22ff2daeb868337cd2ea532a03f58df674f/src/App.js#L25-L29

Here we are using the `setGameBuild` function and expecting that to rerender the component, but that's not happening because react doesn't do rerenders when you pass a setState function the current state. It doesn't seem like the `endGame` variable is the current state, but it is. When we write this line 
```js
const endGame = gameBuild;
```
we are setting `endGame` equal to `gameBuild`. If we mutate either one of those variables, the other one will also change, because they're pointing to the same object in memory. 

Instead, we need to create a copy of `gameBuild` and assign that to `endGame`. There are many ways to accomplish that, but the most straightforward one is like so:
```js
const endGame = {...gameBuild};
```

This way, when we pass `endGame` to `setGameBuild`, react will notice that there's a _new_ variable being assigned to state. 

Docs reference ([link](https://react.dev/reference/react/useState#ive-updated-the-state-but-the-screen-doesnt-update))
